### ISSUE TITLE
AssertionError when trying to run coldtype demo

### ISSUE THREAD

**Issue by ltlnx** [coldtype/coldtype#136]
Hello,

After installing coldtype with the installation procedure at [coldtype.goodhertz.com](https://coldtype.goodhertz.com/) , I tried to run "coldtype demo", which resulted in the following error:

```
    >>> watching... venv/lib/python3.9/site-packages/coldtype/demo/demo.py
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Traceback (most recent call last):
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 791, in reload_and_render
    should_halt = self.reload(trigger)
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 315, in reload
    self.source_reader.reload(
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/reader.py", line 534, in reload
    self.program = run_source(
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/reader.py", line 159, in run_source
    return run_path(str(codepath), init_globals={
  File "/usr/lib64/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/coldtype__demo_tdiii16w.py", line 3, in <module>
    co = Font.Cacheable("assets/ColdtypeObviously.designspace")
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/text/font.py", line 161, in Cacheable
    FontCache[path] = Font(
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/text/font.py", line 95, in __init__
    self.path = Path(normalize_font_path(path))
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/text/font.py", line 71, in normalize_font_path
    raise FontNotFoundException(literal)
coldtype.text.font.FontNotFoundException: /home/ltlnx/projects/coldtype/assets/ColdtypeObviously.designspace

Traceback (most recent call last):
  File "/home/ltlnx/projects/coldtype/venv/bin/coldtype", line 8, in <module>
    sys.exit(main())
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 1662, in main
    Renderer(parser, winmans_class=winmans).main()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 829, in main
    self.start()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 876, in start
    self.winmans.run_loop()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/__init__.py", line 251, in run_loop
    self.last_previews = self.renderer.turn_over()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 1421, in turn_over
    did_preview = self.winmans.turn_over()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/__init__.py", line 205, in turn_over
    did_preview.append(self.glsk.turn_over())
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/glfwskia.py", line 334, in turn_over
    self.reset_extent(extent)
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/glfwskia.py", line 324, in reset_extent
    self.create_surface(extent)
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/glfwskia.py", line 170, in create_surface
    assert self.surface is not None
AssertionError
```

When running the test code from the webpage, the second error still occurs:

```
    >>> watching... test1.py
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Traceback (most recent call last):
  File "/home/ltlnx/projects/coldtype/venv/bin/coldtype", line 8, in <module>
    sys.exit(main())
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 1662, in main
    Renderer(parser, winmans_class=winmans).main()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 829, in main
    self.start()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 876, in start
    self.winmans.run_loop()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/__init__.py", line 251, in run_loop
    self.last_previews = self.renderer.turn_over()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/__init__.py", line 1421, in turn_over
    did_preview = self.winmans.turn_over()
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/__init__.py", line 205, in turn_over
    did_preview.append(self.glsk.turn_over())
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/glfwskia.py", line 334, in turn_over
    self.reset_extent(extent)
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/glfwskia.py", line 324, in reset_extent
    self.create_surface(extent)
  File "/home/ltlnx/projects/coldtype/venv/lib64/python3.9/site-packages/coldtype/renderer/winman/glfwskia.py", line 170, in create_surface
    assert self.surface is not None
AssertionError
```

I'm on Slackware Linux with python 3.9.
```
$ uname -a
Linux localhost.localdomain 6.1.31 #1 SMP PREEMPT_DYNAMIC Tue May 30 16:49:07 CDT 2023 x86_64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz GenuineIntel GNU/Linux

$ python
Python 3.9.16 (main, Mar  8 2023, 02:30:13) 
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by stenson** [comment]
Thanks for trying out Coldtype — the issue with the demo is known (and will be fixed in the next release shortly), but unfortunately the general issue seems to be with the [skia-python library](https://github.com/kyamagu/skia-python), which is used for all graphics rendering. I'd say your best bet might be to try out different versions of skia-python (i.e. downgrading), to see if any work well with your particular linux. I can't say I know much about linux but I have used skia-python successfully in a few different linux environments (on a chromebook, an aws server, and a google colab notebook). To downgrade/install a specific version of skia-python, you can do something like `pip install skia-python==87.3` (using any of the more recent versions of skia-python here https://pypi.org/project/skia-python/#history)
