### ISSUE TITLE
coldtype issues on Windows: truncated viewer and video export not working

### ISSUE THREAD

**Issue by adbac** [coldtype/coldtype#141]
Hello,
I've begun using coldtype and i find it wonderful, especially since I work on Windows and the drawbot library is only available on MacOs... However, I've encountered a few issues that I believe are specific to Windows and sometimes appear in the "Discussions" section of this repo. I don't know if I should open separate issues, but here's the list:
- The viewer only displays the bottom left quarter of the animation or image, but the renders have correct dimensions
_The viewer_
![image](https://github.com/coldtype/coldtype/assets/126618591/79d655c0-04c0-4b7d-9dca-697381de7e4b)
_The code_
```python
from coldtype import *

fnt = Font("animations/Inter.var.ttf")

@animation((1080, 540), timeline=50, bg=hsl(0.6))
def wave(f):
    return (Glyphwise("alternate", lambda g:
        Style(fnt, 200,
              wght=f.adj(-g.i*3).e("seio", 1)))
        .align(f.a.r)
        .f(1))

release = wave.export("h264", loops=4)
```
_One of the renders_
![image](https://github.com/coldtype/coldtype/assets/126618591/9dccc990-4128-4ca9-abbd-647ccf5ebcfa)

- Rendering all the frames of an animation works very well (when pressing a), but pressing r to export the mp4 file throws an error. It's really annoying... I have checked that the ffmpeg py module is installed, should I install the classic ffmpeg software in addition? Here's the error that is thrown:
```
> ffmpeg command == ffmpeg
writing mp4...
Traceback (most recent call last):
  File "C:\Users\adrie\OneDrive\Typographie\_coldtype\venv\lib\site-packages\coldtype\renderer\__init__.py", line 1006, in on_release
    res = fn(all_passes)
  File "C:\Users\adrie\OneDrive\Typographie\_coldtype\venv\lib\site-packages\coldtype\renderable\animation.py", line 308, in _export
    fe.write()
  File "C:\Users\adrie\OneDrive\Typographie\_coldtype\venv\lib\site-packages\coldtype\renderable\animation.py", line 431, in write
    run(self.args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run   
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,        
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable     

! Release failed !
/ release
```
- Minor issue: I have an AZERTY keyboard, but I have to press keys as if I were on a QWERTY one: pressing q for pressing a, a for q

Sorry if I'm not precise enough, don't hesitate to ask for more info

**Comment by stenson** [comment]
Thanks for trying out Coldtype! I haven't heard about the ffmpeg/windows or AZERTY issues before, so those are definitely new to me. I've just tried to figure out how to install ffmpeg on windows but so far can't quite understand it, I'll keep looking into that. Definitely room for improvement on Windows, I just have to admit I don't know a whole lot about Windows generally.

As for the first issue, you should be able to adjust what shows up in the viewer by passing a "window content scale" argument to the coldtype command, like so: `coldtype demo -wcs 1` (the default is to read the content scale from the OS, but I've never been able to figure out why windows reports this as 2 in some cases, which is what seems to be happening here). You can also adjust other things, like having the window float above all others (`-wf 1`) and pinning it to the side of the screen (`-wp E`) to avoid it being cropped by the activity bar (another windows thing I can't figure out). So all in all, you might want something like `coldtype demo -wcs 1 -wp E -wf 1` to get a better set of defaults for windows. (You can also copy the contents of https://github.com/coldtype/coldtype/blob/main/.coldtype.win.py into a file at `~/.coldtype.py` and these will be set as your defaults, so you wouldn't need to pass them on the command line)

I'll break out the AZERTY issue into another issue to figure out, hopefully soon.

**Comment by stenson** [comment]
I also forgot — a temporary fix to get ffmpeg working is to install a precompiled exe for ffmpeg (like the win64 zip here https://github.com/BtbN/FFmpeg-Builds/releases), and then configure coldtype to use that exe, again using the `~/.coldtype.py` configuration file. So, together with those options from above, you could end up with something like this in that file:

```python
WINDOW_PIN = "E"
WINDOW_CONTENT_SCALE = 1
WINDOW_FLOAT = 1

from pathlib import Path
FFMPEG_COMMAND = Path("~/Downloads/ffmpeg-master-latest-win64-gpl/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe").expanduser()
```

I just tried that on my windows setup and it did get an mp4 compiled via ffmpeg (though there is still a small error where coldtype can't open the File Explorer on Windows — but the rendered file should be located next to your coldtype source file in a renders folder)

**Comment by adbac** [comment]
Thanks so much for your quick answer, it all works well now!
