### ISSUE TITLE
pyobjc_setup error when installing coldtype[viewer] on Windows

### ISSUE THREAD

**Issue by fdinsen** [coldtype/coldtype#150]
I am trying to install coldtype[viewer] on my windows PC, following the guide in the docs. However, I am getting the below error when running the command "pip install coldtype[viewer]". I'm getting the same error on two different PCs.

From what I can gather, pyobjc is a Mac-only library, which would explain why it would fail when installing. 

```
Collecting coldtype[viewer]
  Obtaining dependency information for coldtype[viewer] from https://files.pythonhosted.org/packages/8e/ec/d3e34a538054a1277e38af3f6427c60dce71e324d7e8d1fe2b4aabc4fc50/coldtype-0.10.14-py3-none-any.whl.metadata
  Using cached coldtype-0.10.14-py3-none-any.whl.metadata (2.1 kB)
Collecting blackrenderer>=0.6.0 (from coldtype[viewer])
  Using cached blackrenderer-0.6.0-py3-none-any.whl (30 kB)
Collecting fonttools[ufo,unicode] (from coldtype[viewer])
  Obtaining dependency information for fonttools[ufo,unicode] from https://files.pythonhosted.org/packages/0d/0e/b23a19158c918cad2da281350eee227d16abe2655cf85f1adb357a7bb3ff/fonttools-4.44.0-cp312-cp312-win_amd64.whl.metadata
  Using cached fonttools-4.44.0-cp312-cp312-win_amd64.whl.metadata (156 kB)
Collecting fontPens (from coldtype[viewer])
  Using cached fontPens-0.2.4-py2.py3-none-any.whl (19 kB)
Collecting easing-functions (from coldtype[viewer])
  Using cached easing_functions-1.0.4-py3-none-any.whl (15 kB)
Collecting mido (from coldtype[viewer])
  Obtaining dependency information for mido from https://files.pythonhosted.org/packages/b0/0e/b551e09391220208764c00ed2b382e198414329d8b6037eeb54a8008d737/mido-1.3.0-py3-none-any.whl.metadata
  Using cached mido-1.3.0-py3-none-any.whl.metadata (5.1 kB)
Collecting defcon (from coldtype[viewer])
  Obtaining dependency information for defcon from https://files.pythonhosted.org/packages/39/ab/3b83cf25ad9731e11f6e1a77e1ab0d3499f1cb2d71a094fb9acf5be61e28/defcon-0.10.3-py3-none-any.whl.metadata
  Using cached defcon-0.10.3-py3-none-any.whl.metadata (3.5 kB)
Collecting freetype-py (from coldtype[viewer])
  Using cached freetype_py-2.4.0-py3-none-win_amd64.whl (790 kB)
Collecting uharfbuzz>=0.14.0 (from coldtype[viewer])
  Obtaining dependency information for uharfbuzz>=0.14.0 from https://files.pythonhosted.org/packages/61/a9/775d0a1f3f961a7ad956724c5439a96ca3a86183a0826424ccbfe63f482c/uharfbuzz-0.37.3-cp312-cp312-win_amd64.whl.metadata
  Using cached uharfbuzz-0.37.3-cp312-cp312-win_amd64.whl.metadata (2.3 kB)
Collecting python-bidi (from coldtype[viewer])
  Using cached python_bidi-0.4.2-py2.py3-none-any.whl (30 kB)
Collecting requests (from coldtype[viewer])
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting b3denv>=0.0.5 (from coldtype[viewer])
  Obtaining dependency information for b3denv>=0.0.5 from https://files.pythonhosted.org/packages/97/ce/50d486626dbc24ecd7980314b80c0338e792bafec281ebbda27f8f773d1c/b3denv-0.0.9-py3-none-any.whl.metadata
  Using cached b3denv-0.0.9-py3-none-any.whl.metadata (476 bytes)
Collecting glfw (from coldtype[viewer])
  Obtaining dependency information for glfw from https://files.pythonhosted.org/packages/e5/fb/819923400b06aaf5604c62ffc35aa9f37340b2b4ec6e1d7399b1ec2408be/glfw-2.6.2-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-win_amd64.whl.metadata
  Using cached glfw-2.6.2-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-win_amd64.whl.metadata (5.4 kB)
Collecting PyOpenGL (from coldtype[viewer])
  Obtaining dependency information for PyOpenGL from https://files.pythonhosted.org/packages/99/48/00e31747821d3fc56faddd00a4725454d1e694a8b67d715cf20f531506a5/PyOpenGL-3.1.7-py3-none-any.whl.metadata
  Using cached PyOpenGL-3.1.7-py3-none-any.whl.metadata (3.2 kB)
INFO: pip is looking at multiple versions of coldtype[viewer] to determine which version is compatible with other requirements. This could take a while.
Collecting coldtype[viewer]
  Obtaining dependency information for coldtype[viewer] from https://files.pythonhosted.org/packages/ef/65/6009562bcfaa6df4397612477c4653a01bd34c1dd1c47d47e15f9cfc6cc0/coldtype-0.10.13-py3-none-any.whl.metadata
  Using cached coldtype-0.10.13-py3-none-any.whl.metadata (2.1 kB)
  Obtaining dependency information for coldtype[viewer] from https://files.pythonhosted.org/packages/82/1c/e2ab6b8dffe4f80edbcad2172271ecff828bd7106364584a4b9263333f1b/coldtype-0.10.12-py3-none-any.whl.metadata
  Using cached coldtype-0.10.12-py3-none-any.whl.metadata (2.1 kB)
  Obtaining dependency information for coldtype[viewer] from https://files.pythonhosted.org/packages/c4/e6/8e57dae12714602c63a087dc794a6a54c7db1019bc114a02b7f12d422b93/coldtype-0.10.11-py3-none-any.whl.metadata
  Using cached coldtype-0.10.11-py3-none-any.whl.metadata (2.1 kB)
  Obtaining dependency information for coldtype[viewer] from https://files.pythonhosted.org/packages/31/e9/2c94924a7b51989750d3aa5b4dd81f0e862f1757a5e7d9fde58af87eb5dc/coldtype-0.10.10-py3-none-any.whl.metadata
  Using cached coldtype-0.10.10-py3-none-any.whl.metadata (2.1 kB)
  Obtaining dependency information for coldtype[viewer] from https://files.pythonhosted.org/packages/24/a6/09e09782ed82d6acb6717b01dd4b8f2a2f32f54f73a843c92bd74a3f0a18/coldtype-0.10.9-py3-none-any.whl.metadata
  Using cached coldtype-0.10.9-py3-none-any.whl.metadata (2.1 kB)
  Obtaining dependency information for coldtype[viewer] from https://files.pythonhosted.org/packages/de/78/4cb2c4798beb2a4516a8077a109b21595d795cc9b24ea3cd740fb82c68e9/coldtype-0.10.8-py3-none-any.whl.metadata
  Using cached coldtype-0.10.8-py3-none-any.whl.metadata (2.0 kB)
  Using cached coldtype-0.10.7-py3-none-any.whl (472 kB)
INFO: pip is still looking at multiple versions of coldtype[viewer] to determine which version is compatible with other requirements. This could take a while.
  Using cached coldtype-0.10.6-py3-none-any.whl (471 kB)
  Using cached coldtype-0.10.5-py3-none-any.whl (471 kB)
  Using cached coldtype-0.10.4-py3-none-any.whl (469 kB)
  Using cached coldtype-0.10.3-py3-none-any.whl (469 kB)
  Using cached coldtype-0.10.2-py3-none-any.whl (469 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached coldtype-0.10.1-py3-none-any.whl (469 kB)
  Using cached coldtype-0.10.0-py3-none-any.whl (469 kB)
Collecting pyobjc-framework-Cocoa (from coldtype[viewer])
  Using cached pyobjc-framework-Cocoa-10.0.tar.gz (6.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\gamma\OneDrive\Code\Python Coldtype\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\gamma\OneDrive\Code\Python Coldtype\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gamma\OneDrive\Code\Python Coldtype\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gamma\AppData\Local\Temp\pip-build-env-6tgr1042\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gamma\AppData\Local\Temp\pip-build-env-6tgr1042\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\gamma\AppData\Local\Temp\pip-build-env-6tgr1042\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 26, in <module>
        File "C:\Users\gamma\AppData\Local\Temp\pip-install-fod0nq7l\pyobjc-framework-cocoa_9eca6bfee18c4e97bfe162d447e66871\pyobjc_setup.py", line 469, in Extension
          if "clang" in get_config_var("CC"):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: argument of type 'NoneType' is not iterable
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by stenson** [comment]
thanks for reporting that — I don't know why pyobjc would be specified for as a dependency, as it's not even installed on a fresh installation of coldtype on mac — what version of python are you using on windows?

**Comment by stenson** [comment]
ah I see, are you using python 3.12.0? given how many "specialized" dependencies coldtype has (like skia-python and numpy), I usually avoid the .0 release of a new python, as they never seem to work properly. If you are using 3.12.0, could you try with an older Python? I've had success with the latest 3.11

**Comment by fdinsen** [comment]
Reverting to python 3.11.6 fixed the issue, thank you!
