### ISSUE TITLE
ligatures break coldtype to blender workflow when 'Glyphwise' function is used

### ISSUE THREAD

**Issue by arrowtype** [coldtype/coldtype#53]
I’m using code that is very similar to `varfont.py`, but it breaks if I:

1. Specify a font that includes default ligatures, and...
2. Use a string of type that uses a ligature, such as `Refine` or `Waffle`

However, it is working as expected if I use another string that wouldn’t have a ligature (e.g. `Light`). It also works to use the `StSt` function, but then I lose the cool variable axis differences from glyph to glyph.

This is a wild guess, but ... maybe the ligature breaks the indexing, because it collapses two glyphs into one? Maybe there is some way I could handle this in the ColdType function...

Of course, this might also be the expected result, but I was a little surprised by it (then again, I am completely new to this system).

Here’s the traceback I got:

```
>>> resave: proofs/blender-2-vf.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/stephennixon/code/coldtype/coldtype/renderer/__init__.py:682 in _single_thread_render     │
│                                                                                                  │
│    680 │   │   │   │   │   │   │   │   │   │   if pr.name == render.name and pr.last_result:     │
│    681 │   │   │   │   │   │   │   │   │   │   │   render.last_result = pr.last_result           │
│ ❱  682 │   │   │   │   │   │   │   result = render.normalize_result(render.run(rp, self.state))  │
│    683 │   │   │   │   │   │                                                                     │
│    684 │   │   │   │   │   │   if self.state.request:                                            │
│                                                                                                  │
│ /Users/stephennixon/code/coldtype/coldtype/renderable/renderable.py:225 in run                   │
│                                                                                                  │
│   223 │   │   │   return render_pass.fn(*render_pass.args, renderer_state)                       │
│   224 │   │   else:                                                                              │
│ ❱ 225 │   │   │   return render_pass.fn(*render_pass.args)                                       │
│   226 │                                                                                          │
│   227 │   def runpost(self, result, render_pass, renderer_state):                                │
│                                                                                                  │
│ /var/folders/x0/q5zt3sx15ssdz5mjcm9rgvh40000gn/T/coldtype__blender-2-vf_5jf2xhru.py:10 in        │
│ varfont                                                                                          │
│                                                                                                  │
│    8 @b3d_animation(timeline=60)                                                                 │
│    9 def varfont(f):                                                                             │
│ ❱ 10 │   return (Glyphwise("Hifi", lambda i,c:                                                   │
│   11 │   │   Style(fnt, 475,                                                                     │
│   12 │   │   │   wght=f.adj(-i*15).e("seio", 1, rng=(0.98, 0))                                   │
│                                                                                                  │
│ /Users/stephennixon/code/coldtype/coldtype/text/composer.py:261 in Glyphwise                     │
│                                                                                                  │
│   259 │   │   │   if len(test) > 2:                                                              │
│   260 │   │   │   │   #print("_PREV", _prev)                                                     │
│ ❱ 261 │   │   │   │   _next = krn(tkoff, tkon, 2) - _prev #tkoff[0].ambit().w                    │
│   262 │   │   │   │   #print("next", _next)                                                      │
│   263 │   │   │   else:                                                                          │
│                                                                                                  │
│ /Users/stephennixon/code/coldtype/coldtype/text/composer.py:226 in krn                           │
│                                                                                                  │
│   224 │                                                                                          │
│   225 │   def krn(off, on, idx):                                                                 │
│ ❱ 226 │   │   return kx(off, idx) - kx(on, idx)                                                  │
│   227 │                                                                                          │
│   228 │   dps = DraftingPens()                                                                   │
│                                                                                                  │
│ /Users/stephennixon/code/coldtype/coldtype/text/composer.py:223 in kx                            │
│                                                                                                  │
│   221 def Glyphwise(st, styler):                                                                 │
│   222 │   def kx(dps, idx):                                                                      │
│ ❱ 223 │   │   return dps[idx].ambit().x                                                          │
│   224 │                                                                                          │
│   225 │   def krn(off, on, idx):                                                                 │
│                                                                                                  │
│ /Users/stephennixon/code/coldtype/coldtype/pens/datpen.py:520 in __getitem__                     │
│                                                                                                  │
│   518 │                                                                                          │
│   519 │   def __getitem__(self, index):                                                          │
│ ❱ 520 │   │   return self._pens[index]                                                           │
│   521 │                                                                                          │
│   522 │   def indexed_subset(self, indices):                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IndexError: list index out of range
------------------------------
Traceback (most recent call last):
  File "/Users/stephennixon/code/coldtype/coldtype/blender/watch.py", line 83, in modal
    self.render_current_frame(statics=True)
  File "/Users/stephennixon/code/coldtype/coldtype/blender/watch.py", line 29, in render_current_frame
    for _, res in self.sr.frame_results(
  File "/Users/stephennixon/code/coldtype/coldtype/renderer/reader.py", line 352, in frame_results
    res.append([r, r.run_normal(p)])
  File "/Users/stephennixon/code/coldtype/coldtype/renderable/renderable.py", line 272, in run_normal
    self.run(render_pass, renderer_state))
  File "/Users/stephennixon/code/coldtype/coldtype/renderable/renderable.py", line 225, in run
    return render_pass.fn(*render_pass.args)
  File "/var/folders/x0/q5zt3sx15ssdz5mjcm9rgvh40000gn/T/coldtype__blender-2-vf_oklmurrd.py", line 10, in varfont
  File "/Users/stephennixon/code/coldtype/coldtype/text/composer.py", line 261, in Glyphwise
    _next = krn(tkoff, tkon, 2) - _prev #tkoff[0].ambit().w
  File "/Users/stephennixon/code/coldtype/coldtype/text/composer.py", line 226, in krn
    return kx(off, idx) - kx(on, idx)
  File "/Users/stephennixon/code/coldtype/coldtype/text/composer.py", line 223, in kx
    return dps[idx].ambit().x
  File "/Users/stephennixon/code/coldtype/coldtype/pens/datpen.py", line 520, in __getitem__
    return self._pens[index]
IndexError: list index out of range

ran /Users/stephennixon/type-repos/kyrios/proofs/blender-2-vf.py
```

**Comment by stenson** [comment]
ah! very interesting — because Glyphwise is an experimental class at the moment, this is just something it handles very poorly (it currently steps through character-by-character, but if the characters get re-mapped to ligatures, then it does all go haywire) — going to require some significant coding to get this to work, but definitely seems worth it — will update when I've got something

**Comment by stenson** [comment]
actually, just realized there is a workaround currently, you'd just have to pass in your string kind of pre-ligaturized, i.e. if _fi_ is going to become an `f_i` ligature in your font, instead of passing `"fifo"` into Glyphwise as the first argument, you could pass `["fi", "f", "o"]` and it should theoretically work (at least works for me on a font that has an f_i ligature)

**Comment by arrowtype** [comment]
Very cool! Strangely, it seems that for this to work, the "fi" ligature needs at least two items to come after it. So, `Refined` works, but `Refin` and `Refi` do not. Likewise, `Waffled` works, but `Waffle` does not (in the case of an `ffl` ligature).

![image](https://user-images.githubusercontent.com/45946693/126583786-45eac147-ced2-411f-8e14-41262d509b7d.png)

![image](https://user-images.githubusercontent.com/45946693/126584084-bd35163c-a6de-441d-bfe7-9d9e8abd158b.png)
