### ISSUE TITLE
Coldtype demo: No module named 'fontgoggles'

### ISSUE THREAD

**Issue by romashamin** [coldtype/coldtype#88]
I got the next when running `coldtype demo`:

```
Traceback (most recent call last):
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/site-packages/coldtype/text/reader.py", line 17, in <module>
    from fontgoggles.font import getOpener
ModuleNotFoundError: No module named 'fontgoggles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/site-packages/freetype/raw.py", line 49, in <module>
    _lib = ctypes.CDLL(filename)
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libfreetype.dylib, 0x0006): tried: 'libfreetype.dylib' (no such file), '/usr/local/lib/libfreetype.dylib' (no such file), '/usr/lib/libfreetype.dylib' (no such file), '/Users/roma/libfreetype.dylib' (no such file), '/usr/local/lib/libfreetype.dylib' (no such file), '/usr/lib/libfreetype.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/roma/.pyenv/versions/3.10.0/bin/coldtype", line 5, in <module>
    from coldtype.renderer import main
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/site-packages/coldtype/__init__.py", line 4, in <module>
    from coldtype.text import *
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/site-packages/coldtype/text/__init__.py", line 1, in <module>
    from coldtype.text.reader import Style, StyledString, SegmentedString, normalize_font_path, Font, FontNotFoundException
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/site-packages/coldtype/text/reader.py", line 24, in <module>
    from coldtype.fontgoggles.font.otfFont import OTFFont
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/site-packages/coldtype/fontgoggles/font/otfFont.py", line 7, in <module>
    from ..misc.ftFont import FTFont
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/site-packages/coldtype/fontgoggles/misc/ftFont.py", line 5, in <module>
    import freetype
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/site-packages/freetype/__init__.py", line 24, in <module>
    from freetype.raw import *
  File "/Users/roma/.pyenv/versions/3.10.0/lib/python3.10/site-packages/freetype/raw.py", line 52, in <module>
    raise RuntimeError('Freetype library not found')
RuntimeError: Freetype library not found
```

macOS 12.1, Python 3.10.0.

**Comment by romashamin** [comment]
> Are you able to run coldtype with python3.9?

I will try, thank you! 🙂

**Comment by romashamin** [comment]
With python 3.9.9:
```
Traceback (most recent call last):
  File "/Users/roma/.pyenv/versions/3.9.9/bin/coldtype", line 5, in <module>
    from coldtype.renderer import main
  File "/Users/roma/.pyenv/versions/3.9.9/lib/python3.9/site-packages/coldtype/__init__.py", line 27, in <module>
    from coldtype.text import *
  File "/Users/roma/.pyenv/versions/3.9.9/lib/python3.9/site-packages/coldtype/text/__init__.py", line 3, in <module>
    import coldtype.text.composer
  File "/Users/roma/.pyenv/versions/3.9.9/lib/python3.9/site-packages/coldtype/text/composer.py", line 7, in <module>
    from coldtype.text.reader import Style, StyledString, FittableMixin, Font, normalize_font_path, SegmentedString,  _PenClass, _PensClass
  File "/Users/roma/.pyenv/versions/3.9.9/lib/python3.9/site-packages/coldtype/text/reader.py", line 38, in <module>
    from coldtype.fontgoggles.font.otfFont import OTFFont
  File "/Users/roma/.pyenv/versions/3.9.9/lib/python3.9/site-packages/coldtype/fontgoggles/font/otfFont.py", line 7, in <module>
    from ..misc.ftFont import FTFont
  File "/Users/roma/.pyenv/versions/3.9.9/lib/python3.9/site-packages/coldtype/fontgoggles/misc/ftFont.py", line 5, in <module>
    import freetype
  File "/Users/roma/.pyenv/versions/3.9.9/lib/python3.9/site-packages/freetype/__init__.py", line 24, in <module>
    from freetype.raw import *
  File "/Users/roma/.pyenv/versions/3.9.9/lib/python3.9/site-packages/freetype/raw.py", line 39, in <module>
    filename = ctypes.util.find_library('freetype')
  File "/Users/roma/.pyenv/versions/3.9.9/lib/python3.9/site-packages/coldtype/__init__.py", line 16, in find_library
    if res.startswith("/usr/local") and platform.processor() == "arm":
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by stenson** [comment]
Ohh, gotcha, thanks for trying that out. It looks like you're on an M1 computer? I don't think the freetype-py package has updated its prebuilt binaries for the M1 arm arch yet, so you'll either have to install freetype itself (something like `brew install freetype` if you have brew), or you could use an intel python. I'm on an M1 computer as well, using the intel version of Python 3.9, rather than the arm version (the default). It looks like you're using pyenv which I'm not familiar with, but using the python installer from python.org, there's a `python3.9-intel64` version of python that I use to make virtual envs (ala `python3.9-intel64 -m venv venv`) and I haven't had any issues (and seems to run just as fast as the "native" arm Python)

**Comment by romashamin** [comment]
> It looks like you're on an M1 computer?

Yep 🙂

OK, thanks, I’ll try both ways.

**Comment by romashamin** [comment]
Actually, I forgot, I already have `freetype` installed:
```
% brew list | grep freetype
freetype
```

Seems like there’s remains the only option with intel python.

**Comment by stenson** [comment]
I'm now running Coldtype regularly with m1-native python3.10 without any freetype/fontgoggles issues, so going to close this issue
